services:
  postgres:
    image: postgres:16
    container_name: kwve_pg
    restart: unless-stopped
    env_file: ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../sql:/sql:ro
    networks:
      - ${NETWORK_NAME}

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: kwve_os
    restart: unless-stopped
    env_file: ../.env
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "${OPENSEARCH_PORT}:9200"
    volumes:
      - os_data:/usr/share/opensearch/data
      - ../sql:/sql:ro
    networks:
      - ${NETWORK_NAME}

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: kwve_os_dash
    restart: unless-stopped
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - ${NETWORK_NAME}

  minio:
    image: minio/minio:RELEASE.2024-12-07T01-09-49Z
    container_name: kwve_minio
    restart: unless-stopped
    env_file: ../.env
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - ${NETWORK_NAME}

  redis:
    image: redis:7-alpine
    container_name: kwve_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ${NETWORK_NAME}

volumes:
  pg_data:
  os_data:
  minio_data:

networks:
  ${NETWORK_NAME}:
    driver: bridge
