services:
  postgres:
    image: postgres:16
    container_name: kwve_pg
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../sql:/sql:ro
    networks:
      - kwve_net

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: kwve_os
    restart: unless-stopped
    env_file: .env
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ports:
      # ### CHANGED: host port from .env -> container 9200 (fixed by image)
      - "${OPENSEARCH_PORT:-9200}:9200"
    volumes:
      - os_data:/usr/share/opensearch/data
      - ../sql:/sql:ro
    networks:
      - kwve_net

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: kwve_os_dash
    restart: unless-stopped
    environment:
      # ### CHANGED: talk to OpenSearch in-cluster over HTTP on 9200
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      # ### CHANGED: host port from .env -> container 5601
      - "${OPENSEARCH_DASHBOARDS_PORT:-5601}:5601"
    depends_on:
      - opensearch
    networks:
      - kwve_net

  minio:
    image: minio/minio:latest
    container_name: kwve_minio
    restart: unless-stopped
    env_file: .env
    command: server /data --console-address ":9001"   # <= hard-bind console inside container
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

    asr_worker:
    container_name: kwve_asr_worker
    build:
      context: ..
      dockerfile: infra/asr.Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      # Where to look for new audio in MinIO (prefix/folder)
      - ASR_INPUT_PREFIX=incoming/
      # Where to write artifacts in MinIO
      - ASR_ARTIFACT_PREFIX=artifacts/
      # OpenSearch index (already used by your stack)
      - OS_INDEX=kwve-transcripts
      # ASR model & settings (CPU friendly)
      - ASR_MODEL=base.en
      - ASR_BEAM_SIZE=5
      - ASR_VAD=false
      - ASR_POLL_INTERVAL_SEC=20
      # MinIO endpoint pieces assembled from .env:
      # MINIO_HOST is host:port like "minio:9000" INSIDE the compose network.
      # We use the service name "minio" and container port 9000 for in-cluster calls.
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=false
      # OS_URL is internal to the network too; use the service name and port 9200
      - OPENSEARCH_URL=http://opensearch:9200
    depends_on:
      - minio
      - opensearch
    networks:
      - kwve_net

  redis:
    image: redis:7-alpine
    container_name: kwve_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - kwve_net

volumes:
  pg_data:
  os_data:
  minio_data:

networks:
  kwve_net:
    driver: bridge




